### ISSUE TITLE
dd command issue

### ISSUE THREAD

**Issue by SmashingPumpkins** [DerekSelander/LLDB#2]
## dd isn't working for me on Version 8.3.3 (8E3004b) of Xcode

@DerekSelander Thanks for all your hard work and enjoying your book!

(lldb) dd
Traceback (most recent call last):
  File "/usr/local/bin/lldb_commands/disassemble.py", line 37, in handle_command
    output += generateAssemblyFromSymbol(sym, options)
  File "/usr/local/bin/lldb_commands/disassemble.py", line 66, in generateAssemblyFromSymbol
    mnemonic = ds.attrStr(inst.mnemonic.ljust(5), 'red')
  File "/Applications/Xcode8.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python/lldb/__init__.py", line 5220, in __mnemonic_property__
    return self.GetMnemonic (target)
  File "/Applications/Xcode8.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python/lldb/__init__.py", line 5173, in GetMnemonic
    return _lldb.SBInstruction_GetMnemonic(self, *args)
ValueError: invalid null reference in method 'SBInstruction_GetMnemonic', argument 2 of type 'lldb::SBTarget'
(lldb)

**Comment by DerekSelander** [comment]
Hey @SmashingPumpkins thanks for bring that to my attention. Should be fixed on 8b767b44. Cheers.
