### ISSUE TITLE
dd command failed

### ISSUE THREAD

**Issue by sloik** [DerekSelander/LLDB#6]
Env:
Symulator iOS 11.2 iPhone X

Usage:
(lldb) dd 0x10af2df62

Result:
Traceback (most recent call last):
  File "/some/path/lldb/lldb_commands/disassemble.py", line 42, in handle_command
    output += generateAssemblyFromSymbol(sym, options, exe_ctx)
  File "/some/path/lldb/lldb_commands/disassemble.py", line 74, in generateAssemblyFromSymbol
    pc = ds.attrStr('-> ', 'red') if frame.addr == inst.addr else '   '
NameError: global name 'frame' is not defined

**Comment by DerekSelander** [comment]
Thanks, should be addressed in https://github.com/DerekSelander/LLDB/commit/6430b18e47c62c52c592308d73ce66a9d793e6a2
